### ISSUE TITLE
Action: @SarahTannir --> Faire un retour sur l’aide-mémoire

### ISSUE THREAD

**Issue by sjinko** [CUPUM/supervisions#3]
Hi @sarahtannir, could you please do me a service? I have written an aide-mémoire for the future students who want to do their masters‘ at the chair. Could you please have a look at the docx file and make suggestions / comment in review mode ?

The document is on the main directory of this new repo : https://github.com/CUPUM/supervisions/blob/main/koseki-aide_memoire-memoire-20231121.docx

For a quick look, there is also a PDF version on the repo : https://github.com/CUPUM/supervisions/blob/main/koseki-aide_memoire-memoire-20231121.pdf

**Comment by SarahTannir** [comment]
On it @sjinko!

**Comment by SarahTannir** [comment]
Hello @sjinko, I have added my 4 comments here: 
[tannir-koseki-aide_memoire-memoire-20231121.docx](https://github.com/CUPUM/supervisions/files/13452502/tannir-koseki-aide_memoire-memoire-20231121.docx)

Side note: I think it's really important to present the three research interests of the chair somewhere for future students. If not in this aide mémoire, maybe on your profile on recherche UdeM! It's (usually) the first thing we look for.

**Comment by sjinko** [comment]
Hey @SarahTannir, thanks, it is super useful!
